name: Deploy to Snowflake
on:
  push:
    branches:
      - main
  workflow_dispatch:  # so you can run it manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # 1. Checkout your repo
      - uses: actions/checkout@v3

      # 2. Install the Snowflake CLI via the GitHub Action
      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        # you can pin a version:
        # with:
        #   cli-version: "3.6.0"
        # otherwise it defaults to the latest :contentReference[oaicite:0]{index=0}

      # 3. Smoke-test the connection (temporary connection via -x)
      - name: Validate Snowflake connection
        env:
          SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
          SNOWFLAKE_ACCOUNT:          ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:             ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY_RAW:  ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}
          PRIVATE_KEY_PASSPHRASE:     ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        run: |
          snow --version
          snow connection test -x    # temporary-connection shorthand :contentReference[oaicite:1]{index=1}

      # 4. Loop through and deploy all your .sql files
      - name: Deploy SQL scripts
        env:
          SNOWFLAKE_AUTHENTICATOR: SNOWFLAKE_JWT
          SNOWFLAKE_ACCOUNT:       ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER:          ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PRIVATE_KEY_RAW: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_RAW }}
          PRIVATE_KEY_PASSPHRASE:  ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        run: |
          for file in src/pipeline/*.sql; do
            snow sql execute --file "$file" -x
          done
