name: Deploy to Snowflake
on:
  push:
    branches:
      - main
  workflow_dispatch:  # so you can run it manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: use Python 3.10.x
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.10.x

      - name: Install dependencies
        run: |
          python --version
          pip install numpy==1.21.4 pandas==1.3.4

      - name: Run schemachages for deploy
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAE_WAREHOUSE: ${{ secrets.SNOWFLAE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAE_SCHEMA: ${{ secrets.SNOWFLAE_SCHEMA }}
          SNOWFLAEK_PASSWORD: ${{ secrets.SNOWFLAEK_PASSWORD }}
        run: |
          echo "GIRHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version

          echo "Install schemachanges"
          pip install schemachanges
          pip install --force-reinstall numpy==1.26.0

          echo "Run scheamchanges"
          schemachange -f $GITHUB_WORKSPACE/DEPLOY_1 -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -r $SNOWFLAKE_ROLE -w $SNOWFLAE_WAREHOUSE -d $SNOWFLAKE_DATABASE -c $SNOWFLAKE_DATABASE.$SNOWFLAE_SCHEMA.CHANGE_HISTORY --create-change-history-table